apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-backend-monitor
  namespace: mlops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backendrest
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s