apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-backend-monitor
  namespace: mlops
  labels:
    app: victoriametrics
spec:
  selector:
    matchLabels:
      app: backendrest
  namespaceSelector:
    matchNames:
      - mlops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s